{
 "title": "SQL Managed Instance Performance",
 "tags": [ "SQLMI" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "InstanceName",
    "label": "InstanceName",
    "query": "SHOW TAG VALUES  FROM \"sqlserver_server_properties\" WITH KEY=\"sql_instance\""
   }
  ]
 },
 "panels": [
  { "title": "Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "server_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Instance Type",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"SKU\" WHERE \"sql_instance\" =~ /^$InstanceName$/ ",
     "select": [
      [
       { "params": [ "TotalStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"hardware_type\" WHERE \"sql_instance\" =~ /^$InstanceName$/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total  Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "TotalStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Available  Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "AvailableStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "# Databases",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_online" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "SQL Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Batch Requests/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"object\" =~ /SQL Statistics/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      {
       "condition": "AND",
       "key": "object",
       "operator": "=",
       "value": "MSSQL$C8648930B0D8:SQL Statistics"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Transactions/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  { "title": "CPU and Queueing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Resource Pool %CPU Usage Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "%CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT sum(\"value\") FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"object\" =~ /Resource Pool Stats/ AND  \"counter\" = 'CPU usage %') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "CPU usage %" }
     ]
    }
   ]
  },
  {
   "title": "Workload Group - %CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT \"value\" FROM \"sqlserver_performance\" WHERE (\"counter\" = 'CPU usage %' AND \"object\" =~ /Workload Group Stats/ AND \"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter GROUP BY \"instance\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "CPU usage %" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  { "title": "Waits and Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Wait Types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "query": "SELECT non_negative_derivative(\"wait_time_ms\", 1s) FROM \"sqlserver_waitstats\" WHERE (\"sql_instance\" =~ /^$InstanceType.*$/) AND $timeFilter GROUP BY \"wait_type\"",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Signal Wait Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "signal_wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Waiting Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "waiting_tasks_count" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Memory Manager",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT \"value\" FROM \"sqlserver_performance\" WHERE (\"object\" =~ /Memory Manager/ AND \"sql_instance\" =~ /^$InstanceName$/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "object",
       "operator": "=",
       "value": "MSSQL$B60900B20CD7:Memory Manager"
      },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Clerks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_clerk_type",
     "groupBy": [
      { "params": [ "clerk_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_memory_clerks",
     "select": [
      [
       { "params": [ "size_kb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager: Page Life Expectancy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Page life expectancy" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"sqlserver_performance\" WHERE (\"object\"  =~ /Buffer Manager/ AND \"sql_instance\" =~ /^$InstanceName$/ AND \"counter\" =~ /sec/ ) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "object",
       "operator": "=",
       "value": "MSSQL$B60900B20CD7:Buffer Manager"
      },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page lookups/sec" }
     ]
    }
   ]
  },
  {
   "title": "Access Methods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s)  FROM \"sqlserver_performance\" WHERE (\"object\"  =~ /Access Methods/ AND \"sql_instance\" =~ /^$InstanceName$/ AND \"counter\" =~ /sec/ ) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "SQL Statistics / sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_counter",
     "groupBy": [
      { "params": [ "counter" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(\"value\", 1s) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$InstanceName$/ AND \"object\" =~ /General Statistics/) AND $timeFilter GROUP BY \"counter\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      {
       "condition": "AND",
       "key": "object",
       "operator": "=",
       "value": "MSSQL$C8648930B0D8:General Statistics"
      }
     ]
    }
   ]
  }
 ]
}