{
 "title": "SQL  Managed Instance HADR",
 "tags": [ "SQLMI" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "InstanceName",
    "label": "InstanceName",
    "query": "SHOW TAG VALUES  FROM \"sqlserver_server_properties\" WITH KEY=\"sql_instance\""
   }
  ]
 },
 "panels": [
  { "title": "Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "server_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Instance Type",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"SKU\" WHERE \"sql_instance\" =~ /^$InstanceName$/ ",
     "select": [
      [
       { "params": [ "TotalStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"hardware_type\" WHERE \"sql_instance\" =~ /^$InstanceName$/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total  Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "TotalStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Available  Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "AvailableStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "# Databases",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_online" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Availability Group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "HADR Waits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_type",
     "groupBy": [
      { "params": [ "wait_type" ], "type": "tag" }
     ],
     "measurement": "sqlserver_waitstats",
     "query": "SELECT non_negative_derivative(\"wait_time_ms\", 1s) FROM \"sqlserver_waitstats\" WHERE (\"sql_instance\" =~ /^$InstanceName$/) AND (\"wait_type\" =~ /HADR/) AND $timeFilter GROUP BY \"wait_type\"",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Log  Flushed Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Bytes Flushed/sec" }
     ]
    }
   ]
  },
  {
   "title": "Log Flushes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "counter", "operator": "=", "value": "Log Flushes/sec" },
      { "condition": "AND", "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Availability Group - Transaction Delay",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Transaction Delay" }
     ]
    }
   ]
  },
  {
   "title": "Availability Group - Bytes Sent  to Replica/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Bytes Sent to Replica/sec" }
     ]
    }
   ]
  },
  {
   "title": "Availability Group - Flow Control ms/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Flow Control Time (ms/sec)" }
     ]
    }
   ]
  }
 ]
}