{
 "title": "SQL Managed Instance Storage",
 "tags": [ "SQLMI" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "InstanceName",
    "label": "InstanceName",
    "query": "SHOW TAG VALUES  FROM \"sqlserver_server_properties\" WITH KEY=\"sql_instance\""
   }
  ]
 },
 "panels": [
  { "title": "Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "cpu_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "server_memory" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Instance Type",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"SKU\" WHERE \"sql_instance\" =~ /^$InstanceName$/ ",
     "select": [
      [
       { "params": [ "TotalStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "query": "SHOW TAG VALUES WITH KEY = \"hardware_type\" WHERE \"sql_instance\" =~ /^$InstanceName$/ ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total  Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "TotalStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Available  Storage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "mbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "AvailableStorageMB" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "# Databases",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_server_properties",
     "select": [
      [
       { "params": [ "db_online" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Database File Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true
  },
  {
   "title": "Data File Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Data File(s) Size (KB)" }
     ]
    }
   ]
  },
  {
   "title": "Log File Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Size (KB)" }
     ]
    }
   ]
  },
  {
   "title": "Log File Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "instance" ], "type": "tag" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log File(s) Used Size (KB)" }
     ]
    }
   ]
  },
  { "title": "Database IO Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Read Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Write Bytes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Reads/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Writes/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_database_name",
     "groupBy": [
      { "params": [ "database_name" ], "type": "tag" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$InstanceName$/" }
     ]
    }
   ]
  }
 ]
}